import Header from "@/components/Header";
import PomodoroClock from "@/components/PomodoroClock";
import ToDoList from "@/components/ToDoList";
import { db } from "@/firebase";
import { doc, getDoc } from "firebase/firestore";
import { getProviders, getSession } from "next-auth/react";
import Head from "next/head";

interface Props {
  listdata: ToDoList[];
  completedToDos: ToDoList[];
}

export default function Home({ listdata, completedToDos }: Props) {
  return (
    <>
      <Head>
        <title>Ultimate Pomodoro Login to save todo's</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
      </Head>
      <header className="h-[6vh] max-h-[6vh]">
        <Header />
      </header>
      <main className="bg-black">
        <section className="lg:flex">
          <PomodoroClock />
          {/* second component */}
          <ToDoList listdata={listdata} completedToDos={completedToDos} />
        </section>
        <section>{/* page 2 */}</section>
      </main>
    </>
  );
}

export async function getServerSideProps(context: any) {
  const providers = await getProviders();
  const session = await getSession(context);
  const ToDoListData = await getDoc(doc(db, `${session?.user.uid}`, "Default"))
    .then((res) => res.data()?.ToDoList)
    .catch((err) => err.message);

  const completedToDos = await getDoc(
    doc(db, `${session?.user.uid}`, "Default")
  )
    .then((res) => res.data()?.CompletedToDos)
    .catch((err) => err.message);

  return {
    props: {
      providers,
      session,
      listdata: ToDoListData || null,
      completedToDos: completedToDos || null,
    },
  };
}
