import Header from "@/components/Header";
import PomodoroClock from "@/components/PomodoroClock";
import ToDoList from "@/components/ToDoList";
import { db } from "@/firebase";
import { doc, getDoc } from "firebase/firestore";
import { getProviders, getSession } from "next-auth/react";
import { DocumentContext } from "next/document";
import Head from "next/head";

interface Props {
  listdata: ToDoList[]
}

export default function Home({ listdata }: Props) {
  
  return (
    <>
      <Head>
        <title>Ultimate Pomodoro</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
      </Head>
      <header>
        <Header />
      </header>
      <main className="bg-black">
        <section>
          <PomodoroClock />
          {/* second component */}
          <ToDoList listdata={listdata} />
        </section>
        <section>{/* page 2 */}</section>
      </main>
    </>
  );
}

export async function getServerSideProps(context: DocumentContext) {
  const providers = await getProviders();
  const session = await getSession(context);
  const ToDoListData = await getDoc(doc(db, "UserData", `${session?.user.uid}`))
    .then((res) => res.data()?.ToDoList)
    .catch((err) => err.message);

  return {
    props: {
      providers,
      session,
      listdata: ToDoListData,
    },
  };
}
